services:
  event-server:
    build:
      context: ./event_server
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - PORT=3000
      - DB_USER=webvitals
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_NAME=db
      - DB_URL=postgresql://webvitals:password@postgres:5432/db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=webvitals
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webvitals -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

  proxy:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - event-server
